### ISSUE TITLE
Use SREM to discard set members?

### ISSUE THREAD

**Issue by ze-phyr-us** [brainix/pottery#1]
This library looks great! I was going to need something like this in about a week so thank you for saving me time :-)

I was wondering why not discard set members with [SREM](http://redis.io/commands/srem) rather than SMOVE+DEL.

**Comment by brainix** [comment]
Thank you for your kind words and insightful feedback!

You're absolutely right - SREM is the way to go.  My implementation was embarrassing and wrong.  Look how much you've simplified my code:

https://github.com/brainix/pottery/commit/42e77eb59267549ac1976c05c4d72b16b86b6583

I've bumped version numbers and rereleased to PyPI.  Closing this out for now.

**Comment by gourneau** [comment]
:+1:
