### ISSUE TITLE
Consider removing .python-version

### ISSUE THREAD

**Issue by RazerM** [brainix/pottery#12]
Having this file ties the repository to a specific virtualenv (assuming you're using pyenv-virtualenv), which means contributors have to use workarounds (i.e. deleting the file and remembering not to commit the change).

I use pyenv but not pyenv-virtualenv; this file breaks pyenv for me since it can't find the `pottery` version.

Please ignore this issue if you don't agree, just a minor pain point!

**Comment by brainix** [comment]
Hi, @RazerM!

Excellent suggestion, thanks!  I'll remove `.python-version` tonight.  Hopefully that'll ease local development.

Thanks again,
Raj

**Comment by brainix** [comment]
Hi again, @RazerM.

I apologize that this has taken me so long.  I've addressed your feedback (among other things) in this [pull request](https://github.com/brainix/pottery/pull/33), which I've [merged into master](https://github.com/brainix/pottery/commit/6c5d0a17ec6095a4cd279a7e662545c86396a7d3).  As of Python 3.6, `pyenv-virtualenv` is marked deprecated anyway, in favor of `python3 -m venv`.

Please let me know if you have any additional feedback, and thanks!
Raj
