### ISSUE TITLE
Does sorted sets support?And how to use it?Or how to find a alternative way?

### ISSUE THREAD

**Issue by patterson163** [brainix/pottery#130]
@brainix  Recently,I had been using your lib.I found it's a smart and easy tool to a redis freshman.But I want to use sorted sets,and I can not find the way.Could you please help me?

**Comment by brainix** [comment]
There’s currently no way to create a sorted set, although this wouldn’t be too difficult to implement. Let me think about how I’d do this and get back to you in a couple of days.

**Comment by patterson163** [comment]
Thank you for your help.

**Comment by jeffreybrowning** [comment]
Looking at this: https://github.com/redis/redis/issues/135#issuecomment-2361996

It seems to need sorted sets. Has there been movement on this @brainix . Or a different way to use pottery to do the suggested workaround.

**Comment by peedrr** [comment]
Hey @brainix, this library looks very impressive, you've done some great work!

I just want to add my +1 to a Sorted Sets implementation.

Many thanks
