### ISSUE TITLE
Is cluster support on schedule?

### ISSUE THREAD

**Issue by hisi-SmallFish** [brainix/pottery#29]
I build a redis cluster, so I need a python client that support it.

**Comment by brainix** [comment]
Hi, @hisi-SmallFish.

Thanks for your interest, but I believe that cluster support is better handled in a lower-level library, and not within Pottery itself.  Have you looked at [redis-py-cluster](http://redis-py-cluster.readthedocs.io/en/master/)?

Thanks,
Raj
