### ISSUE TITLE
Asyncio Ideas

### ISSUE THREAD

**Issue by plataux** [brainix/pottery#453]
Thanks for the great project, very clean, very solid.

Have you considered, an asyncio implementation? or do you think that the potential complexity won't pay off for practical usage?

Thanks again!

**Comment by brainix** [comment]
Thanks for the praise, @plataux. It means a lot. 😄 

I have considered an asyncio implementation. I think it could make a nice addition to Pottery, and [aioredis](https://github.com/aio-libs/aioredis-py) looks well supported. But I don't have any asyncio use cases myself.

What are your use cases, so that I might better think through the asyncio implementation? Do you use `Redlock`, `RedisDict`, or some other features of Pottery?

**Comment by plataux** [comment]
Oh yea, the recent release of aioredis 2.0 is a big reason why I am planning to use Redis more and more as a primary data store, and it makes aio-pottery a very attractive idea.

High Level Usecase:

In general, web frameworks like [starlette](https://github.com/encode/starlette) can be used to build fully asyncio applications. In other words, you have a very well defined number of system threads throughout the lifetime of your application, no matter the load, which means very efficient, and more importantly, **predictable** consumption of system resources.  If a starlette application involves tons of websockets to manage chatrooms, messages, attachments across a few hundred to a few thousand clients,  Async Pottery would not just be a luxory, but a necessity.

More Specific Usecase:

I have a customer project that involves a large number of users arbitrarily scheduling periodic network-bound tasks. I'm considering using a modified/minified edition of [apscheduler](https://github.com/agronholm/apscheduler), Redis and Redlocks for a distributed task scheduling/execution system that is distributed for scalability, and resilience. If you have 5 scheduling/executor machines trying to coordinate on the schedule, Redlock is needed, and I prefer it to be Async.

By the way, [Celery](https://github.com/celery/celery) is out of the question in my opinion. I've used it for a few years, and is not a great choice for the above distributed use case, in my opinion.

Indeed, Redlock is the most important piece, and I have already coded an async Redlock based on your design, just inlined all of the Redlock code in one class to easily comprehend and test it, for now.

**Comment by ericcgu** [comment]
which system resources specifically? task scheduling is often CPU bound and async is not going to help. Can you elaborate on your opinion on why Celery is not great choice for distributed task scheduling?

**Comment by plataux** [comment]
You are right that CPU intensive tasks are best executed outside of any asyncio event loop. In fact, they are best executed outside of the Python Interpreter entirely.

Anyway, I was referring to RAM resources associated with threads, and their context switching-overhead. The Tasks that I was referring to are more business-level tasks, such as send/receive files, processing text files, update and move data across databases over the network or local storage, call HTTP APIs regularly, FTP operations, scrape entire websites periodically, send / receive SMTP email. All I/O Bound stuff.

Celery is good for distributed task **execution**, IMO. However, when it comes to **scheduling**, you can only run Celery Beat on a single process and a single machine, which is a single point of failure. You can try running Celery Beat on two machines sharing the same Schedule on a central MySQL database for example, but how do you deal with both schedulers running the same task twice? 

They will need to coordinate by using locks, which is where Redlock comes in. Coordination between schedulers has been extensively discussed and requested on [apscheduler](https://github.com/agronholm/apscheduler) issues board.

Anyway, if you have different thoughts or experiences, please share.

**Comment by ericcgu** [comment]
Celery beat is not the best, I agree with you there.  I put celery beat in a container with a health check / k8s liveliness probe. If that thread/process/machine goes unhealthy, kublet will kill and spawn another beat container immediately on the next available compute resource. The failed job will go to dead letter queue that is saved in HA mongo and may even be auto-retried. When you are speaking of single point of failure, I'm interpreting that as typical host infrastructure failures, which docker and kubernetes solves quite elegantly.

**Comment by brainix** [comment]
Commenting for anyone who might come across this issue in the future... 💡 

I've never done any asyncio programming before... but @plataux has written an excellent library called [Purse](https://github.com/plataux/purse). Purse includes an asyncio dict, set, list/deque, and Redlock. I'm learning asyncio programming myself by reading Purse's clean source code. 🎉 

So if you're interested in async Pottery-like functionality, take a look at Purse! 👏🏾
