### ISSUE TITLE
self.key is converted from str to bytes

### ISSUE THREAD

**Issue by devinbarry** [brainix/pottery#51]
```
Exception ignored in: <bound method _Common.__del__ of MyRedisDict>
Traceback (most recent call last):
  File "/home/axion/envs/arbitrage/lib/python3.5/site-packages/pottery/base.py", line 43, in __del__
    if self.key.startswith(self._RANDOM_KEY_PREFIX):
TypeError: startswith first arg must be bytes or a tuple of bytes, not str
```

**Comment by brainix** [comment]
Thanks for the bug report.  I'll take a look at this tonight and report back.

**Comment by brainix** [comment]
@devinbarry - I'm having a hard time reproducing this.  Would you please post a full code snippet that exercises this problem?  I think that the fix is easy once I understand, but I'm not sure how your `RedisDict`'s key could be `bytes`.  Thanks in advance!
