### ISSUE TITLE
Cannot import name 'Script' from 'redis.client' with 'redis-4.1.0'

### ISSUE THREAD

**Issue by wy-z** [brainix/pottery#552]
**Describe the bug**
Cannot import name 'Script' from 'redis.client' with 'redis-4.1.0'

**To Reproduce**
Use pottery with 'redis-4.1.0'

**Additional context**
'redis.client.Script' has been removed.
Look at the following code
https://github.com/redis/redis-py/commit/12f45ee2d8cc2c15b89ae579bf27b448ef0d1c2e#diff-3161b005adfa1f5266a9736bffb5ede9d14e2ab40937cb241bc16ca5647df79d

https://github.com/redis/redis-py/issues/1748

**Comment by wy-z** [comment]
Maybe we should import `Script` from `redis.commands.core`

**Comment by jasonTu** [comment]
Met the same issue too.

**Comment by brainix** [comment]
Thanks to your detailed bug report, @wy-z, the fix was easy! And thanks for confirming, @jasonTu.

I've just released [Pottery 2.2.2](https://github.com/brainix/pottery/releases/tag/v2.2.2) which includes the bug fix.
