### ISSUE TITLE
A dictionary inside RedisDict

### ISSUE THREAD

**Issue by Sorrow2** [brainix/pottery#6]
Hello.
Why this doesnt work and how can i get it work?

```
>>> from pottery import RedisDict
>>> users_dict = RedisDict(redis=redis, key='users_dict')
>>> users_dict
RedisDict{34324144: {'lastname': '', 'notification': 0, 'accesslevel': 1, 'firstname': 'First Name', 'username': 'user'}}
>>> users_dict[34324144]['accesslevel']
1
>>> users_dict[34324144]['accesslevel'] = 4
>>> users_dict[34324144]['accesslevel']
1
```

**Comment by Sorrow2** [comment]
``` tmpdic = users_dict[34324144]
                            tmpdic['accesslevel'] = 4
                            users_dict[id] = tmpdic ```

**Comment by brainix** [comment]
Hi, @Sorrow2.  I apologize for my delayed response; I've been busy helping my sister and my brother in-law move into their new house.

You've discovered an interesting problem!  This exposes an underlying issue with Python's container implementation.  I'm not sure that I'll be able to fix this, and for now, I believe that your workaround makes sense.  I'll take a look at Python's container implementation and see if there's any way that I can update the parent container if any child container is modified.

Thanks for the report, and I'll comment again in the next couple of days!

**Comment by Sorrow2** [comment]
Any update?

**Comment by brainix** [comment]
I've thought deeply about this problem, and the only way to solve it is to use some crazy technique (like metaclasses, or monkey patching Python's built-in types) which probably wouldn't be worth the complexity.

I think the best solution is exactly the one that you proposed.  If you want to change a child of a Pottery container, directly set that child on the Pottery container.

Thank you!

**Comment by roskoN** [comment]
Hey @brainix ,

have you considered the possibility to enable a RedisDict within another RedisDict (or any other pottery containers)?

The way I imagine this is `_Encodable` in `encode` and `decode` methods we check if `value` has a type `_Common` or `Base`. In `encode`, we just save something like the following for the pottery container: 
```
{
    "pottery_type": "RedisDict",
    "redis_key": "rediskey"
}
```

The trickier part is in `decode`. We would instantiate a new pottery container using the specified pottery type, redis key and `redis`-instance of the "parent". The only possible problem is that `_Encodable` and `_Common` need to be merged to be able to access the `redis` attribute of the parent.

What do you think? Am I missing something?

Cheers

**Comment by brainix** [comment]
Hi, @roskoN!

Wow...  I'd never even considered it.  But what you're saying sounds awesome.  I think that it's totally feasible, and your suggested design/implementation sounds clean and maintainable.

If I were to implement this, would you use it?  Thanks for the feedback!

**Comment by roskoN** [comment]
Hey @brainix 

By the way, something I should have written earlier, thank you for your work on pottery!

I am happy to see that you like my suggestion. My use case is a RedisList inside a RedisDict and right now I am using the aforementioned workaround with re-assigning the key each time the child container is changed. So, if this gets implemented, it would let me delete a couple of lines of code. 

Cheers
